main:
  project_name: depl_fastAPI
  experiment_name: dev
  deployed_url: "https://deploying-a-machine-learning-model-with-3y1u.onrender.com"

data:
  data_path: data/census.csv
  processed_data_path: data/processed/processed_data.csv
  train_path: data/splits/train.csv
  test_path: data/splits/test.csv
  model_path: models/rfc_model.pkl
  slicing_output: output_metrics/slice_output.txt
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.2
  # Fraction of remaining data to use for validation
  val_size: 0.2
  random_seed: 42
  # Column to use for stratification (use "none" for no stratification)
  stratify_by: "salary"
data_check:
  kl_threshold: 0.2
  # Threshold for Kolomorov-Smirnov test
  ks_alpha: 0.05
pipeline_param:
  random_forest:
    n_estimators: 100
    criterion: squared_error
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    min_weight_fraction_leaf: 0.0
    max_features: 0.1
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    min_impurity_split: null
    bootstrap: true
    # DO not change the following
    oob_score: true
    # Here -1 means all available cores
    n_jobs: -1
    # This is a different random seed than main.random_seed,
    # because this is used only within the RandomForest
    random_state: 42
    verbose: 0
    warm_start: false
    class_weight: "balanced"
    ccp_alpha: 0.0
    max_samples: null
features:
  numerical:
    - 'age'
    - 'fnlgt'
    - 'capital_gain'
    - 'capital_loss'
    - 'hours_per_week'
  non_ordinal_categ:
    - 'marital_status'
    - 'occupation'
    - 'relationship'
    - 'race'
    - 'sex'
    - 'workclass'
    - 'native_country'
    - 'education'

sample_data:
  valid_data:
    "age": 25
    "workclass": "Private"
    "fnlgt": 77516
    "education": "Bachelors"
    "education_num": 13
    "marital_status": "Never-married"
    "occupation": "Prof-specialty"
    "relationship": "Not-in-family"
    "race": "White"
    "sex": "Male"
    "capital_gain": 0
    "capital_loss": 0
    "hours_per_week": 40
    "native_country": "United-States"
  incomplete_data:
     "age": 30
     "fnlgt": 12345
     "education_num": 9
     "capital_gain": 0
     "capital_loss": 0
     "native_country": "United-States"
  data_above_50k:
    "age": 40
    "workclass": "Private"
    "fnlgt": 121772
    "education": "Assoc-voc"
    "education_num": 11
    "marital_status": "Married-civ-spouse"
    "occupation": "Craft-repair"
    "relationship": "Husband"
    "race": "Asian-Pac-Islander"
    "sex": "Male"
    "capital_gain": 7298
    "capital_loss": 0
    "hours_per_week": 40
    "native_country": "United-States"
  data_below_50k:
    "age": 25
    "workclass": "Private"
    "fnlgt": 226802
    "education": "11th"
    "education_num": 7
    "marital_status": "Never-married"
    "occupation": "Machine-op-inspct"
    "relationship": "Own-child"
    "race": "Black"
    "sex": "Male"
    "capital_gain": 0
    "capital_loss": 0
    "hours_per_week": 40
    "native_country": "United-States"
